### ISSUE TITLE
Changing to SVG results in errors

### ISSUE THREAD

**Issue by steersteer** [JakobGlock/Generative-Art#1]
Hi,
I wanted to use this for SVGs but changing to use SVG results in:

`C:\Users\whywo\anaconda3\python.exe "F:/OneDrive - Heriot-Watt University/Code/Python/pycairo/Mosaic_Circles.py"
Traceback (most recent call last):
  File "F:/OneDrive - Heriot-Watt University/Code/Python/pycairo/Mosaic_Circles.py", line 126, in <module>
    height
__main__.IOError: error while writing to output stream`

**Comment by JakobGlock** [comment]
Looks like you are using Windows, I have only tested this on Linux (Ubuntu 18.04 & 20.04 specifically).

**Comment by entangledothers** [comment]
This error occurs also in Ubuntu (Pop!OS) 20.04. Cairo was installed via " conda install -c conda-forge pycairo" (only way to get pycairo working in a conda setting as far as I can tell) if that helps, python 3.7. 

edit: For some reason there is a permissions error, changing the script output to './' and it suddenly worked.

**Comment by JakobGlock** [comment]
Hmmm, strange. I think the issue might be down to the folders not existing which I save the SVG files in, for example:

`surface = cairo.SVGSurface(
                "Images/Mosaic_Circles/0-svg/" + str(fileName) + ".svg",
                width,
                height
        )
`

`Images/Mosaic_Circles/0-svg/` does not exist.
